package main

var adminHTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#f5f6fa">
  <link rel="icon" href="/assets/porta-mark.svg" type="image/svg+xml">
  <title>Porta Control</title>
  <style>
    @font-face{font-family:"Mona Sans";src:url("/assets/mona-sans.woff2") format("woff2-variations");font-style:normal;font-weight:200 900;font-display:swap}
    :root{color-scheme:light;font-family:"Mona Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--bg:#f5f6fa;--surface:#fff;--ink:#171923;--muted:#717684;--line:#e6e8ee;--soft:#f0f1f5;--violet:#6558ed;--violet-soft:#eeecff;--green:#23a875;--red:#dc5364;--shadow:0 18px 50px rgba(35,40,68,.08);font-feature-settings:"cv11","ss01","ss03";font-synthesis:none}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink)}button,input{font:inherit}button{cursor:pointer}.hidden{display:none!important}
    .login-page{min-height:100vh;display:grid;grid-template-columns:minmax(340px,.82fr) 1.18fr;background:var(--surface)}.login-panel{display:flex;align-items:center;justify-content:center;padding:28px}.login-box{width:min(380px,100%)}.logo{display:flex;align-items:center;gap:9px;font-size:14px;font-weight:780;letter-spacing:-.025em}.logo-mark{width:30px;height:30px;filter:drop-shadow(0 7px 10px rgba(23,25,35,.16))}.login-box h1{margin:36px 0 10px;font-size:36px;line-height:1.03;letter-spacing:-.052em}.login-box>p{margin:0 0 23px;color:var(--muted);font-size:14px;line-height:1.55}.field{display:grid;gap:6px;margin:14px 0}.field label{color:#545967;font-size:10px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}.field input,.search{width:100%;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--ink);padding:10px 12px;outline:none;transition:.18s ease}.field input:focus,.search:focus{border-color:#978ef5;box-shadow:0 0 0 3px rgba(101,88,237,.1)}.login-note{display:flex;gap:8px;margin-top:16px;color:#8a8e9a;font-size:10px;line-height:1.45}.login-note svg{flex:0 0 auto;margin-top:1px}
    .login-art{position:relative;margin:12px;border-radius:22px;background:#11131c;overflow:hidden}.login-art:before{content:"";position:absolute;inset:-20%;background:radial-gradient(circle at 30% 30%,rgba(113,217,207,.9),transparent 18%),radial-gradient(circle at 58% 48%,rgba(102,88,237,.9),transparent 31%),radial-gradient(circle at 74% 72%,rgba(234,112,171,.62),transparent 22%);filter:blur(18px);animation:drift 12s ease-in-out infinite alternate}.art-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(black,transparent 85%)}.art-copy{position:absolute;left:clamp(26px,5vw,58px);right:clamp(26px,5vw,58px);bottom:clamp(28px,6vw,62px);color:white}.art-copy small{font-size:10px;font-weight:750;letter-spacing:.16em;text-transform:uppercase;color:#c7c4ee}.art-copy h2{max-width:520px;margin:13px 0 10px;font-size:clamp(34px,4.3vw,56px);line-height:1;letter-spacing:-.06em}.art-copy p{max-width:450px;margin:0;color:#c5c7d0;font-size:14px;line-height:1.55}
    .primary,.secondary,.danger,.ghost{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:36px;border-radius:9px;padding:8px 12px;font-weight:680;transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.primary{border:0;background:var(--ink);color:#fff;box-shadow:0 7px 18px rgba(23,25,35,.15)}.primary:hover{transform:translateY(-1px);box-shadow:0 10px 22px rgba(23,25,35,.2)}.secondary,.ghost,.danger{border:1px solid var(--line);background:var(--surface);color:#444957}.secondary:hover,.ghost:hover{background:#f7f7fa}.danger{color:var(--red);border-color:#f0dadd}.danger:hover{background:#fff5f6}.wide{width:100%}
    .app{display:grid;grid-template-columns:200px minmax(0,1fr);min-height:100vh}.sidebar{position:sticky;top:0;height:100vh;padding:20px 17px;border-right:1px solid var(--line);background:rgba(255,255,255,.88);backdrop-filter:blur(18px)}.side-nav{display:grid;gap:6px;margin-top:32px}.nav-item{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:9px;color:#777b87;font-size:12px;font-weight:620}.nav-item.active{background:var(--violet-soft);color:#5549da}.nav-item svg{width:16px}.side-footer{position:absolute;left:17px;right:17px;bottom:18px;padding-top:14px;border-top:1px solid var(--line)}.connection{display:flex;align-items:center;gap:8px;color:#747987;font-size:10px}.connection:before{content:"";width:7px;height:7px;border-radius:50%;background:#32b97e;box-shadow:0 0 0 4px rgba(50,185,126,.12)}
    .content{width:min(1200px,100%);margin:auto;padding:22px clamp(20px,3.5vw,42px) 40px}.topbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:34px}.crumb{color:#8a8e99;font-size:11px}.admin-chip{display:flex;align-items:center;gap:8px;color:#656a77;font-size:11px}.avatar{display:grid;place-items:center;width:27px;height:27px;border-radius:8px;background:#e9e7ff;color:#574bd6;font-size:9px;font-weight:800}
    .hero{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:22px}.eyebrow{color:var(--violet);font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.hero h1{margin:7px 0 7px;font-size:clamp(32px,4vw,42px);line-height:1;letter-spacing:-.052em}.hero p{max-width:560px;margin:0;color:var(--muted);font-size:12px;line-height:1.5}
    .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:20px}.stat{padding:14px;border:1px solid var(--line);border-radius:13px;background:var(--surface);box-shadow:0 4px 14px rgba(40,45,70,.03)}.stat-head{display:flex;align-items:center;justify-content:space-between;color:#7f8491;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.stat-icon{display:grid;place-items:center;width:24px;height:24px;border-radius:8px;background:#f2f1ff;color:var(--violet)}.stat strong{display:block;margin-top:8px;font-size:25px;line-height:1;letter-spacing:-.04em}.stat small{display:block;margin-top:5px;color:#9599a4;font-size:9px}
    .toolbar{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:15px}.toolbar-left{display:flex;align-items:center;gap:10px;flex:1}.search-wrap{position:relative;width:min(300px,100%)}.search-wrap svg{position:absolute;left:13px;top:50%;translate:0 -50%;color:#9498a3}.search{height:40px;padding-left:38px;font-size:12px}.filters{display:flex;padding:3px;border:1px solid var(--line);border-radius:11px;background:#ebedf2}.filter{border:0;border-radius:8px;background:transparent;padding:7px 12px;color:#7a7e8a;font-size:11px;font-weight:680}.filter.active{background:white;color:#303440;box-shadow:0 2px 8px rgba(35,40,65,.08)}.section-count{color:#8d919d;font-size:11px}
    .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{position:relative;padding:14px;border:1px solid var(--line);border-radius:13px;background:var(--surface);box-shadow:0 5px 18px rgba(39,44,68,.035);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.card:hover{transform:translateY(-1px);border-color:#d8d5f7;box-shadow:var(--shadow)}.card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.identity{display:flex;gap:9px;min-width:0}.client-avatar{display:grid;place-items:center;flex:0 0 auto;width:33px;height:33px;border-radius:10px;background:linear-gradient(145deg,#eeeaff,#e7f7f5);color:#5d51dd;font-size:11px;font-weight:800}.card h2{overflow:hidden;margin:0 0 3px;font-size:14px;letter-spacing:-.02em;text-overflow:ellipsis;white-space:nowrap}.status{display:inline-flex;align-items:center;gap:5px;color:var(--green);font-size:9px;font-weight:700}.status:before{content:"";width:5px;height:5px;border-radius:50%;background:currentColor}.status.off{color:#989ca7}.card-menu{border:0;background:transparent;color:#969aa5;font-size:18px;line-height:1}
    .capacity{margin:14px 0 12px}.capacity-row{display:flex;justify-content:space-between;margin-bottom:6px;color:#858a96;font-size:9px}.track{height:4px;border-radius:999px;background:#eceef3;overflow:hidden}.fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,#6b5cf0,#8b7ef7)}.devices{min-height:52px;border-top:1px solid var(--line);padding-top:8px}.device{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:5px 0}.device-info{display:flex;align-items:center;gap:7px;min-width:0}.device-icon{display:grid;place-items:center;flex:0 0 auto;width:24px;height:24px;border-radius:7px;background:#f1f2f6;color:#747987}.device-name{overflow:hidden;font-size:10px;font-weight:680;text-overflow:ellipsis;white-space:nowrap}.device-time{margin-top:1px;color:#a0a3ad;font-size:8px}.icon-button{display:grid;place-items:center;width:25px;height:25px;border:0;border-radius:7px;background:transparent;color:#a1a4ae}.icon-button:hover{background:#f2f3f6;color:var(--red)}.empty-devices{padding:9px 0;color:#9a9ea9;font-size:9px}.actions{display:flex;gap:6px;margin-top:9px;padding-top:9px;border-top:1px solid var(--line)}.actions button{min-height:30px;padding:6px 9px;font-size:9px}.empty{grid-column:1/-1;padding:52px 20px;text-align:center;border:1px dashed #d9dce4;border-radius:15px;background:rgba(255,255,255,.45)}.empty-icon{display:grid;place-items:center;width:42px;height:42px;margin:0 auto 12px;border-radius:13px;background:var(--violet-soft);color:var(--violet)}.empty strong{display:block;font-size:13px}.empty p{margin:6px 0 0;color:#9296a1;font-size:10px}
    dialog{width:min(460px,calc(100% - 28px));border:1px solid var(--line);border-radius:20px;background:var(--surface);color:var(--ink);padding:0;box-shadow:0 32px 100px rgba(26,29,48,.24)}dialog::backdrop{background:rgba(27,29,40,.42);backdrop-filter:blur(5px)}.modal{padding:25px}.modal-mark{display:grid;place-items:center;width:39px;height:39px;margin-bottom:20px;border-radius:12px;background:var(--violet-soft);color:var(--violet)}.modal h2{margin:0;font-size:23px;letter-spacing:-.035em}.modal p{margin:8px 0 22px;color:var(--muted);font-size:12px;line-height:1.6}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:24px}.token{padding:14px;border:1px solid #d9d6f7;border-radius:12px;background:#f7f6ff;color:#4f44c9;word-break:break-all;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace}.notice{position:fixed;right:22px;bottom:22px;z-index:10;max-width:360px;padding:12px 15px;border:1px solid #303440;border-radius:11px;background:#1c1f2a;color:white;box-shadow:0 15px 45px rgba(20,22,35,.25);font-size:11px;opacity:0;translate:0 10px;pointer-events:none;transition:.2s ease}.notice.show{opacity:1;translate:0 0}
    @keyframes drift{from{transform:translate3d(-2%,-1%,0) scale(1)}to{transform:translate3d(4%,3%,0) scale(1.08)}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.login-art:before{animation:none}.card,.primary,.notice{transition:none}}
    @media(max-width:900px){.login-page{grid-template-columns:1fr}.login-art{display:none}.app{grid-template-columns:1fr}.sidebar{position:static;height:auto;padding:14px 18px;border-right:0;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.side-nav,.side-footer{display:none}.content{padding-top:18px}.topbar{margin-bottom:28px}}
    @media(max-width:700px){.login-panel{align-items:flex-start;padding:84px 22px 22px}.content{padding-inline:13px}.hero{align-items:stretch;flex-direction:column;gap:14px}.hero .primary{width:100%}.stats{grid-template-columns:repeat(3,1fr)}.stat small{display:none}.toolbar{align-items:stretch;flex-direction:column}.toolbar-left{align-items:stretch;flex-direction:column}.search-wrap{width:100%}.filters{align-self:flex-start}.grid{grid-template-columns:1fr}.topbar{margin-bottom:24px}.actions{flex-wrap:wrap}}
  </style>
</head>
<body>
  <section id="login" class="login-page">
    <div class="login-panel"><div class="login-box">
      <div class="logo"><img class="logo-mark" src="/assets/porta-mark.svg" alt="">Porta Control</div>
      <h1>Welcome back.</h1><p>Manage client access from a private control surface designed to stay out of the way.</p>
      <div class="field"><label for="admin-token">Admin token</label><input id="admin-token" type="password" autocomplete="current-password" placeholder="Paste your admin token" onkeydown="if(event.key==='Enter')login()"></div>
      <button class="primary wide" onclick="login()">Open dashboard <span aria-hidden="true">→</span></button>
      <div class="login-note"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/></svg><span>Your token is kept only in this browser tab and is never embedded in the page.</span></div>
    </div></div>
    <div class="login-art"><div class="art-grid"></div><div class="art-copy"><small>Private gateway management</small><h2>Simple access.<br>Clear control.</h2><p>Create client credentials, define device capacity, and keep every connection organized.</p></div></div>
  </section>
  <main id="app" class="app hidden">
    <aside class="sidebar">
      <div class="logo"><img class="logo-mark" src="/assets/porta-mark.svg" alt="">Porta Control</div>
      <nav class="side-nav"><div class="nav-item active"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>Client access</div></nav>
      <div class="side-footer"><div class="connection">Gateway available</div></div>
    </aside>
    <section class="content">
      <header class="topbar"><div class="crumb">Control panel <span aria-hidden="true">/</span> Clients</div><div class="admin-chip"><span class="avatar">AD</span>Administrator</div></header>
      <section class="hero"><div><div class="eyebrow">Access management</div><h1>Client overview</h1><p>Issue individual credentials, control device capacity, and review enrollments from one focused workspace.</p></div><button class="primary" onclick="openCreate()">＋ New client</button></section>
      <section class="stats">
        <article class="stat"><div class="stat-head">Total clients<span class="stat-icon">◎</span></div><strong id="client-count">0</strong><small>Managed access groups</small></article>
        <article class="stat"><div class="stat-head">Enabled<span class="stat-icon">✓</span></div><strong id="enabled-count">0</strong><small>Accepting new sessions</small></article>
        <article class="stat"><div class="stat-head">Devices<span class="stat-icon">◇</span></div><strong id="device-count">0</strong><small>Currently enrolled</small></article>
      </section>
      <section class="toolbar">
        <div class="toolbar-left"><div class="search-wrap"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="search" class="search" placeholder="Search clients or devices" oninput="render()"></div><div class="filters"><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="enabled">Enabled</button><button class="filter" data-filter="disabled">Disabled</button></div></div>
        <div id="section-count" class="section-count"></div>
      </section>
      <section id="clients" class="grid"></section>
    </section>
  </main>
  <dialog id="client-dialog"><form class="modal" onsubmit="saveClient(event)"><div class="modal-mark">＋</div><h2 id="dialog-title">New client</h2><p>One secure token can enroll multiple devices up to the limit you choose.</p><input id="edit-id" type="hidden"><div class="field"><label for="client-name">Client name</label><input id="client-name" maxlength="80" required placeholder="e.g. Product team"></div><div class="field"><label for="device-limit">Device limit</label><input id="device-limit" type="number" min="1" max="100" value="5" required></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeDialog()">Cancel</button><button class="primary" type="submit">Save client</button></div></form></dialog>
  <dialog id="token-dialog"><div class="modal"><div class="modal-mark">✓</div><h2>Client token ready</h2><p>Copy this token now. For security, only its hash is stored and it cannot be displayed again.</p><div id="token-value" class="token"></div><div class="modal-actions"><button class="secondary" onclick="copyToken()">Copy token</button><button class="primary" onclick="document.getElementById('token-dialog').close()">Done</button></div></div></dialog>
  <div id="notice" class="notice" role="status"></div>
  <script>
    let token=sessionStorage.getItem('porta-admin-token')||'',clients=[],filter='all';
    const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===204)return null;const body=await r.json().catch(()=>({error:'Request failed'}));if(!r.ok)throw new Error(body.error||'Request failed');return body};
    async function login(){const entered=document.getElementById('admin-token').value.trim();if(entered)token=entered;if(!token){show('Enter the admin token');return}try{await load();sessionStorage.setItem('porta-admin-token',token);document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden')}catch(e){sessionStorage.removeItem('porta-admin-token');show(e.message)}}
    async function load(){const data=await api('/api/clients');clients=data.clients;render()}
    const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
    const relative=value=>{const seconds=Math.max(0,(Date.now()-new Date(value))/1000);if(seconds<60)return'just now';if(seconds<3600)return Math.floor(seconds/60)+'m ago';if(seconds<86400)return Math.floor(seconds/3600)+'h ago';return Math.floor(seconds/86400)+'d ago'};
    function render(){document.getElementById('client-count').textContent=clients.length;document.getElementById('enabled-count').textContent=clients.filter(c=>c.enabled).length;document.getElementById('device-count').textContent=clients.reduce((n,c)=>n+c.device_count,0);const q=document.getElementById('search')?.value.trim().toLowerCase()||'';const visible=clients.filter(c=>(filter==='all'||(filter==='enabled')===c.enabled)&&(!q||c.name.toLowerCase().includes(q)||c.devices.some(d=>d.id.toLowerCase().includes(q))));document.getElementById('section-count').textContent=visible.length+' shown';const root=document.getElementById('clients');if(!visible.length){root.innerHTML='<div class="empty"><span class="empty-icon">◇</span><strong>No clients found</strong><p>'+(clients.length?'Try another search or filter.':'Create your first client to issue secure access.')+'</p></div>';return}root.innerHTML=visible.map(c=>{const pct=Math.min(100,Math.round(c.device_count/c.max_devices*100));return '<article class="card"><div class="card-head"><div class="identity"><span class="client-avatar">'+esc(initials(c.name))+'</span><div><h2>'+esc(c.name)+'</h2><span class="status '+(c.enabled?'':'off')+'">'+(c.enabled?'Enabled':'Disabled')+'</span></div></div><span class="card-menu">•••</span></div><div class="capacity"><div class="capacity-row"><span>Device capacity</span><span>'+c.device_count+' / '+c.max_devices+'</span></div><div class="track"><div class="fill" style="width:'+pct+'%"></div></div></div><div class="devices">'+(c.devices.length?c.devices.slice(0,3).map(d=>'<div class="device"><div class="device-info"><span class="device-icon">◇</span><div><div class="device-name">'+esc(d.id)+'</div><div class="device-time">Seen '+relative(d.last_seen)+'</div></div></div><button class="icon-button" title="Forget enrollment" data-action="device" data-client="'+c.id+'" data-device="'+encodeURIComponent(d.id)+'">×</button></div>').join(''):'<div class="empty-devices">No enrolled devices yet</div>')+(c.devices.length>3?'<div class="empty-devices">+'+(c.devices.length-3)+' more devices</div>':'')+'</div><div class="actions"><button class="secondary" data-action="edit" data-client="'+c.id+'">Edit</button><button class="secondary" data-action="rotate" data-client="'+c.id+'">Rotate token</button><button class="secondary" data-action="toggle" data-client="'+c.id+'">'+(c.enabled?'Disable':'Enable')+'</button><button class="danger" data-action="delete" data-client="'+c.id+'">Delete</button></div></article>'}).join('')}
    function openCreate(){document.getElementById('edit-id').value='';document.getElementById('dialog-title').textContent='New client';document.getElementById('client-name').value='';document.getElementById('device-limit').value='5';document.getElementById('client-dialog').showModal();setTimeout(()=>document.getElementById('client-name').focus(),50)}
    function openEdit(id){const c=clients.find(x=>x.id===id);document.getElementById('edit-id').value=id;document.getElementById('dialog-title').textContent='Edit client';document.getElementById('client-name').value=c.name;document.getElementById('device-limit').value=c.max_devices;document.getElementById('client-dialog').showModal()}
    function closeDialog(){document.getElementById('client-dialog').close()}
    async function saveClient(e){e.preventDefault();const id=document.getElementById('edit-id').value,name=document.getElementById('client-name').value,max_devices=Number(document.getElementById('device-limit').value);try{if(id){const c=clients.find(x=>x.id===id);await api('/api/clients/'+id,{method:'PUT',body:JSON.stringify({name,max_devices,enabled:c.enabled})});show('Client updated')}else{const result=await api('/api/clients',{method:'POST',body:JSON.stringify({name,max_devices})});showToken(result.token)}closeDialog();await load()}catch(e){show(e.message)}}
    async function toggle(id){const c=clients.find(x=>x.id===id);try{await api('/api/clients/'+id,{method:'PUT',body:JSON.stringify({name:c.name,max_devices:c.max_devices,enabled:!c.enabled})});show(c.enabled?'Client disabled':'Client enabled');await load()}catch(e){show(e.message)}}
    async function rotate(id){if(!confirm('Rotate this token? Existing devices will need the new token on their next connection.'))return;try{const r=await api('/api/clients/'+id+'/token',{method:'POST'});showToken(r.token)}catch(e){show(e.message)}}
    async function removeClient(id){if(!confirm('Delete this client and prevent future connections?'))return;try{await api('/api/clients/'+id,{method:'DELETE'});show('Client deleted');await load()}catch(e){show(e.message)}}
    async function removeDevice(client,id){if(!confirm('Forget this device enrollment? It can enroll again if it still has the client token.'))return;try{await api('/api/clients/'+client+'/devices/'+id,{method:'DELETE'});show('Device enrollment removed');await load()}catch(e){show(e.message)}}
    function showToken(value){document.getElementById('token-value').textContent=value;document.getElementById('token-dialog').showModal()}
    async function copyToken(){try{await navigator.clipboard.writeText(document.getElementById('token-value').textContent);show('Token copied to clipboard')}catch(e){show('Copy the token manually')}}
    function show(message){const n=document.getElementById('notice');n.textContent=message;n.classList.add('show');clearTimeout(show.timer);show.timer=setTimeout(()=>n.classList.remove('show'),3200)}
    document.querySelector('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});
    document.getElementById('clients').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.client;({edit:()=>openEdit(id),rotate:()=>rotate(id),toggle:()=>toggle(id),delete:()=>removeClient(id),device:()=>removeDevice(id,b.dataset.device)}[b.dataset.action]||(()=>{}))()});
    if(token)login();
  </script>
</body>
</html>`
